name: work_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.0.0 <3.0.0"

analyzer:
  enable-experiment:
    - non-nullable
    - control-flow-collections

dependencies:
  flutter:
    sdk: flutter
  custom_bottom_navigation_bar: ^0.0.1
  cupertino_icons: ^1.0.0
  custom_navigation_bar: ^0.8.1
  flutter_icons: ^1.1.0
  firebase_core: ^1.0.4
  firebase_auth: ^1.2.0
  firebase_analytics: ^8.1.0
  firebase_database: ^6.1.2
  cloud_firestore: ^1.0.6
  provider: ^5.0.0
  model: ^0.1.3
  flutter_spinkit: ^5.0.0
  table_calendar: ^3.0.0
  shared_preferences: ^2.0.5
  device_info: ^0.4.2+6
  flutter_form_builder: ^6.0.1
  flutter_riverpod: ^0.14.0+3
  flutter_svg: ^0.22.0
  flutter_swiper: ^1.1.6
  firebase_helpers: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/

